"""Immutable source-evidence contracts for future Candidate Formation."""

from playlist_narrative_engine.candidate_formation.schemas import (
    CANDIDATE_EVIDENCE_SCHEMA_VERSION,
    CandidateSourceEvidenceArtifact,
    ContextInputEvidence,
    EvidenceObservation,
    EvidenceState,
    FamiliarityEvidenceArtifact,
    FamiliarityEvidenceRecord,
    LocalTasteEvidenceArtifact,
    ObjectiveContextEvidenceArtifact,
    ObjectiveContextEvidenceRecord,
    TasteEvidenceRecord,
    TrackFeatureEvidenceArtifact,
    TrackFeatureEvidenceRecord,
    UnitIntervalEvidence,
)
from playlist_narrative_engine.candidate_formation.formation_schemas import (
    CANDIDATE_FIELD_ORDER,
    CANDIDATE_FORMATION_SCHEMA_VERSION,
    WITHHOLDING_REASON_EXPLANATIONS,
    WITHHOLDING_REASON_PRECEDENCE,
    CandidateFieldEvidence,
    CandidateFieldName,
    CandidateFormationArtifact,
    CandidateFormationPolicy,
    CandidateFormationRequest,
    CandidateFormationSummary,
    FormationBasis,
    FormedCandidateEntry,
    PreferenceMappingEntry,
    PreferenceMappingRule,
    WithheldCandidateEntry,
    WithholdingReason,
    WithholdingReasonCode,
)
from playlist_narrative_engine.candidate_formation.former import (
    CandidateFormer,
    serialize_candidate_formation,
)
from playlist_narrative_engine.candidate_formation.integration import (
    derive_formed_candidate_pool,
    serialize_formed_candidate_pool,
)
from playlist_narrative_engine.candidate_formation.integration_schemas import (
    FORMED_CANDIDATE_POOL_SCHEMA_VERSION,
    CandidateFormationTrace,
    FormedCandidatePoolView,
)
from playlist_narrative_engine.candidate_formation.serialization import (
    serialize_candidate_source_evidence,
)

__all__ = [
    "CANDIDATE_EVIDENCE_SCHEMA_VERSION",
    "CANDIDATE_FIELD_ORDER",
    "CANDIDATE_FORMATION_SCHEMA_VERSION",
    "WITHHOLDING_REASON_EXPLANATIONS",
    "WITHHOLDING_REASON_PRECEDENCE",
    "CandidateFieldEvidence",
    "CandidateFieldName",
    "CandidateFormationArtifact",
    "CandidateFormationPolicy",
    "CandidateFormationRequest",
    "CandidateFormationSummary",
    "CandidateFormationTrace",
    "CandidateFormer",
    "CandidateSourceEvidenceArtifact",
    "ContextInputEvidence",
    "EvidenceObservation",
    "EvidenceState",
    "FamiliarityEvidenceArtifact",
    "FamiliarityEvidenceRecord",
    "FormationBasis",
    "FORMED_CANDIDATE_POOL_SCHEMA_VERSION",
    "FormedCandidateEntry",
    "FormedCandidatePoolView",
    "LocalTasteEvidenceArtifact",
    "ObjectiveContextEvidenceArtifact",
    "ObjectiveContextEvidenceRecord",
    "PreferenceMappingEntry",
    "PreferenceMappingRule",
    "TasteEvidenceRecord",
    "TrackFeatureEvidenceArtifact",
    "TrackFeatureEvidenceRecord",
    "UnitIntervalEvidence",
    "WithheldCandidateEntry",
    "WithholdingReason",
    "WithholdingReasonCode",
    "derive_formed_candidate_pool",
    "serialize_candidate_formation",
    "serialize_candidate_source_evidence",
    "serialize_formed_candidate_pool",
]
